### ISSUE TITLE
how to get this paper which from ISSCC 2019 

### ISSUE THREAD

**Issue by hisrg** [fengbintu/Neural-Networks-on-Silicon#18]
Please tell me how to get this paper 'A 65nm 236.5nJ/Classification Neuromorphic Processor with 7.5% Energy Overhead On-Chip Learning Using Direct Spike-Only Feedback' tks

**Comment by q437241998** [comment]
I also want to get this paper, please help.

**Comment by abhishek-t-naive** [comment]
You can write to the authors and see if they can provide you with a copy
