### ISSUE TITLE
demo of a network

### ISSUE THREAD

**Issue by han-qiu** [fengbintu/Neural-Networks-on-Silicon#3]
In your description of **Going Deeper with Embedded FPGA Platform for Convolutional Neural Network**,
you said these: "The FPGA runs VGG16-SVD without reconfiguring its resources"

So the author actually implemented a demo of the whole network using the resources of a single FPGA.
I'm wondering are there any other papers that did this.

Thank you!

**Comment by fengbintu** [comment]
Thank you for your comments. Since FPGA'16, many works have been done on acceleraing a whole CNN/RNN network, like another OpenCL-based design in FPGA'16, Caffine in ICCAD'16 and so on.
