### ISSUE TITLE
Add Vathys to "Industry Contributions"?

### ISSUE THREAD

**Issue by sixsamuraisoldier** [fengbintu/Neural-Networks-on-Silicon#6]
Stanford EE380 Talk for more info: https://youtu.be/4nSn0JhZX18

Full disclosure: I'm the co-founder.

**Comment by kumasento** [comment]
@sixsamuraisoldier It is a quite interesting and enlightening talk, thanks for sharing.

**Comment by sixsamuraisoldier** [comment]
Thanks! You're welcome :)

**Comment by fengbintu** [comment]
@sixsamuraisoldier There have been many products from industry recently, so it's difficult for me include them all right now. The talk is interesting, and I hope to see your product next year.

**Comment by sixsamuraisoldier** [comment]
@fengbintu No problem, we plan to ship something in 2018, will keep you updated.

**Comment by blueardour** [comment]
The 2017 is deemed as the meta year of the NPUs. 
Huawei integrate a NPU on their Kirin970. There are also lots of startups to develop such a chip.
For example, the 'thinker' from Tsinghua University,  the DeePhi Tech, the nationalchip company,  the Horizon Robotics. Publications from ISCA, HPCA, Micro and ISSCC witness the surge of various architectures about acceleration of the deep learning algorithms.

@sixsamuraisoldier So, could you give some introduction about the advantages of the Vpathy compared with others? Is there any PPA(performance/power/area) data on classic networks, such as alexnet, vgg, resnet?

**Comment by sixsamuraisoldier** [comment]
@blueardour Yup!

Without a doubt, there are a ton of DL accelerator chips popping up all over the place.

Our advantage is a **power-performance product advantage of 10X** on the classic net such as ResNets.
How we do this is primarily by reducing data movement (~90% of the power and performance bottleneck is there), check our Stanford EE380 talk for more info: https://youtu.be/4nSn0JhZX18

**Comment by blueardour** [comment]
@sixsamuraisoldier  Thanks for the interesting talk.

The Vathys chip is astonishing nice for its performance. As far as I can remember the die size is about 600 mm^2 with drop-in replacement of Nvidia card. Meaning that the chip could be used as both inference and training.

I have several concerns:
1. As a domain specific asic accelerator, the flexibility of Vathys may be less than GPUs or CPUs. When a custom defined layer is proposed, is there way for the Vathys chip to add the support easily?
For example, just update the SDK without change the hardware.
With respect to the fact that developers might not want to open source their custom layers. Could they have the ability to develop the SDK plugin to support their newly proposed layer by themselves?

2. Embedded platforms, such as the cellphones, drones, LoT need high power efficiency AI processors not just only high performance ones. Besides, they might only need the inference function. Thus logic for training might be cut out with consideration of cost. 
So is there any plan to march to the embedded platform market, by developing some thing like a Vathys-lite version of chip?

Sorry if any sensitive topic.

**Comment by sixsamuraisoldier** [comment]
@blueardour 

Thanks! Let me try and answer your questions.

1. Flexibility/programmability is a foremost concern in all deep learning processors. Different companies have different ways of providing this programmability. The way that this works in Vathys processors is by leveraging the computational graph abstraction. The processor itself is programmable like a dataflow machine (and implemented in a CGRA-esque manenr in hardware). If you need a new layer type, simply express it as a composition of simpler nodes (e.g. multiplies, adds, etc.) and the graph compiler takes care of the rest, akin to how TRIPS or EDGE would do it.

2. Of course, and even in high performance domains, power is of paramount importance since this is a relatively easily parallelizable workload, meaning that we're primarily limited by power since we could always just throw more resources at the problem to try and alleviate it. In that respect we have (at the moment) much higher power efficiency than anything else on the market and we expect the "edge inference" market to be a very important market for us. Actually we are in talks with a major company (NDA) in one of those fields. Because our 600mm^2 die is essentially a sea of processing elements, we can cut it up into smaller (e.g. 6x 100mm^2 dice or 10x 60mm^2 dice) and simply use those. That is our plan for the low power, high performance edge inference market.

Hope I answered your questions and let me know if you have any more!

Thanks,
Tapa
